language: node_js
node_js:
- node

before_script:
- openssl aes-256-cbc -K $encrypted_641eef2f1849_key -iv $encrypted_641eef2f1849_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv secrets.yaml src/backend
- npm install -g gulp

script: gulp build

deploy:
  provider: gae
  project: weather-beacon
  config: dist/app.yaml
  keyfile: client-secret.json
  skip_cleanup: true
  default: true
